---

- name: Check if app already deployed
  ansible.builtin.stat:
    path: "{{ rails_app_dir }}/Gemfile"
  register: deploy

- name: Ensure the base directory exists {{ rails_app_base_dir }}
  ansible.builtin.file:
    path: "{{ rails_app_base_dir }}"
    state: directory
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0755'
  when: not deploy.stat.exists

# NOTE: disable sudo here so that ssh-agent forwarding to github will work,
#       be sure to have local .ssh/config setup with 'ForwardAgent yes' for each host
- name: Clone the github repo
  become: false
  ansible.builtin.git:
    repo: "{{ rails_app_git_repo }}"
    dest: "{{ rails_app_shortname }}"
    version: "{{ rails_app_git_branch }}"
    accept_hostkey: true
  when: not deploy.stat.exists

- name: Move the repo into place as the deployment
  ansible.builtin.command:
    cmd: mv -fT {{ rails_app_shortname }} {{ rails_app_dir }}
  when: not deploy.stat.exists

- name: Fix the deployed code ownership
  ansible.builtin.file:
    dest: "{{ rails_app_dir }}"
    state: directory
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    recurse: true
  when: not deploy.stat.exists

- name: Make a symlink to current to fake out capistrano-git_deploy
  ansible.builtin.file:
    src: "{{ rails_app_dir }}"
    path: "{{ rails_app_base_dir }}/current"
    state: link
  when: not deploy.stat.exists

- name: Make a symlink for convenience
  ansible.builtin.file:
    src: "{{ rails_app_dir }}"
    path: /home/{{ rails_app_user }}/{{ rails_app_env }}
    state: link
  when: not deploy.stat.exists
