---

- name: Install package dependencies for {{ rails_app_shortname }}
  apt:
    name: "{{ rails_app_pkg_dependencies }}"
    state: present

- import_tasks: rails_app_user.yml
  tags:
    - rails_app_user

- import_tasks: deploy.yml
  tags:
    - deploy

- import_tasks: vhost.yml
  tags:
    - vhost

- import_tasks: vhost_redirect.yml
  when: rails_app_vhost_redirect
  tags:
    - vhost

- import_tasks: configure.yml
  tags:
    - security
    - envvars

- import_tasks: postgresql.yml
  tags:
    - postgres
  when: rails_app_db_adapter == 'postgresql'

- import_tasks: mysql.yml
  tags:
    - mysql
  when: rails_app_db_adapter == 'mysql'

- import_tasks: logrotate.yml
  tags:
    - logs
  when: rails_app_log_rotation
