---

- name: Install package dependencies for {{ rails_app_shortname }}
  apt:
    name: "{{ rails_app_pkg_dependencies }}"
    state: present

- include: rails_app_user.yml
  tags:
    - rails_app_user

- include: deploy.yml
  tags:
    - deploy

- include: vhost.yml
  tags:
    - vhost

- include: vhost_redirect.yml
  tags:
    - vhost

- include: configure.yml
  tags:
    - security

- include: postgresql.yml
  tags:
    - postgres
  when: rails_app_db_adapter == 'postgresql'

- include: mysql.yml
  tags:
    - mysql
  when: rails_app_db_adapter == 'mysql'

- include: logrotate.yml
  tags:
    - logs
  when: rails_app_log_rotation
