---

- name: Install package dependencies for {{ rails_app_shortname }}
  ansible.builtin.apt:
    name: "{{ rails_app_pkg_dependencies }}"
    state: present

- name: Import user configuration tasks
  ansible.builtin.import_tasks: rails_app_user.yml
  tags:
    - rails_app_user

- name: Import deployment tasks
  ansible.builtin.import_tasks: deploy.yml
  tags:
    - deploy

- name: Import nginx vhost tasks
  ansible.builtin.import_tasks: vhost.yml
  tags:
    - vhost

- name: Import nginx vhost redirect tasks
  ansible.builtin.import_tasks: vhost_redirect.yml
  when: rails_app_vhost_redirect
  tags:
    - vhost

- name: Import rails app configuration tasks
  ansible.builtin.import_tasks: configure.yml
  tags:
    - security
    - envvars

- name: Import postgres tasks
  ansible.builtin.import_tasks: postgresql.yml
  tags:
    - postgres
  when: rails_app_db_adapter == 'postgresql'

- name: Import logrotate tasks
  ansible.builtin.import_tasks: logrotate.yml
  tags:
    - logs
  when: rails_app_log_rotation
