---

- name: Install package dependencies for mysql2 gem
  apt:
    name: libmariadbclient-dev
    state: present

- name: Setup mysql db for the {{ rails_app_user }} rails app
  mysql_db:
    name: "{{ rails_app_db_name }}"
    state: present
    login_user: "{{ rails_app_mysql_root_user }}"
    login_password: "{{ rails_app_mysql_root_password }}"
    login_host: "{{ rails_app_mysql_host }}"
  when: rails_app_db_provision

- name: Setup mysql user for the {{ rails_app_user }} rails app
  mysql_user:
    name: "{{ rails_app_db_user }}"
    password: "{{ rails_app_db_password }}"
    host: "{{ rails_app_mysql_host }}"
    priv: "{{ rails_app_db_name }}.*:ALL"
    state: present
    login_user: "{{ rails_app_mysql_root_user }}"
    login_password: "{{ rails_app_mysql_root_password }}"
    login_host: "{{ rails_app_mysql_host }}"
  when: rails_app_db_provision

- name: Write the database.yml
  template:
    src: database.mysql.yml.j2
    dest: "{{ rails_app_dir }}/config/database.yml"
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0440'
