---

- name: Add user for {{ rails_app_user }}
  ansible.builtin.user:
    name: "{{ rails_app_user }}"
    shell: /bin/bash

- name: Install the authorized keys for {{ rails_app_shortname }} deployers
  ansible.posix.authorized_key:
    user: "{{ rails_app_user }}"
    key: "{{ rails_app_deployer_keys | join('\n') }}"
    exclusive: true
  tags:
    - security

- name: Add .bash_profile for {{ rails_app_user }} so that RAILS_ENV always set
  ansible.builtin.template:
    src: bash_profile
    dest: /home/{{ rails_app_user }}/.bash_profile
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0644'
  tags:
    - postgres

# from https://gist.github.com/maxim/871e611d4bc02c633c67
- name: Ensure github.com is a known host for {{ rails_app_user }}
  ansible.builtin.lineinfile:
    dest: ~{{ rails_app_user }}/.ssh/known_hosts
    create: true
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0600'

- name: Add .gitconfig for {{ rails_app_user }}
  ansible.builtin.copy:
    src: gitconfig
    dest: ~{{ rails_app_user }}/.gitconfig
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0644'

- name: Add .irbrc for {{ rails_app_user }}
  ansible.builtin.copy:
    src: irbrc
    dest: ~{{ rails_app_user }}/.irbrc
    owner: "{{ rails_app_user }}"
    group: "{{ rails_app_user }}"
    mode: '0644'
  when: rails_app_install_irbrc
