---

- name: Install the vhost redirect(s) for {{ rails_app_site }}
  ansible.builtin.template:
    src: vhost_redirect.j2
    dest: /etc/nginx/sites-available/{{ rails_app_site }}_redirect
    mode: '0644'
  notify:
    - Restart nginx

- name: Enable the virtual host redirects for {{ rails_app_site }}
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/{{ rails_app_site }}_redirect
    src: /etc/nginx/sites-available/{{ rails_app_site }}_redirect
    state: link
  notify:
    - Restart nginx
