---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted
  listen: 'restart postgres services'

- name: Restart pgbouncer
  ansible.builtin.service:
    name: pgbouncer
    state: restarted
  when: rails_app_db_enable_pgbouncer|bool
  listen: 'restart postgres services'
