# dropped off by ansible, edit in ansible, not here ...

# use existing profile
if [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

# support --binstubs for bundler
if [ -d "{{ rails_app_dir }}/bin" ] ; then
    export PATH="{{ rails_app_dir }}/bin:$PATH"
fi

# default editor, -w means don't wrap, and -z means it can be suspended
export EDITOR="/bin/nano -w -z"

# view rails logs in technicolor
export LESS='-R'

export RAILS_ENV={{ rails_app_env }}

{% if rails_app_db_host %}
export PGHOST={{ rails_app_db_host }}
{% endif %}
